# Generated by Django 2.2.13 on 2020-08-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PastData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BigIntegerField()),
                ('confirmed_today', models.BigIntegerField()),
                ('active', models.BigIntegerField()),
                ('active_today', models.BigIntegerField()),
                ('recovered', models.BigIntegerField()),
                ('recovered_today', models.BigIntegerField()),
                ('deaths', models.BigIntegerField()),
                ('deaths_today', models.BigIntegerField()),
                ('tests', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('state', models.ManyToManyField(to='status.State')),
            ],
        ),
    ]
