# Generated by Django 2.2.13 on 2020-08-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20200807_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statedata',
            name='tests',
        ),
    ]
