# Generated by Django 2.2.13 on 2020-08-07 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_remove_statedata_tests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statedata',
            options={'ordering': ['-active', 'timestamp'], 'verbose_name': 'States Data', 'verbose_name_plural': 'States Data'},
        ),
    ]
