# Generated by Django 2.2.13 on 2020-08-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_auto_20200807_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statedata',
            name='active',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='statedata',
            name='active_today',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='statedata',
            name='confirmed',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='statedata',
            name='confirmed_today',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='statedata',
            name='deaths',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='statedata',
            name='deaths_today',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='statedata',
            name='location',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='statedata',
            name='recovered',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='statedata',
            name='recovered_today',
            field=models.BigIntegerField(),
        ),
    ]
